---
- name: create network 
  community.docker.docker_network:
    name: "{{item}}"
  loop:
    - app_net
    - web_net

- name: deploy wordpress Compose stack
  community.docker.docker_compose:
    project_src: "{{root_dir}}/wordpress/"
    files:
      - docker-compose.yaml
  tags: deploy_compose