---
- name: Creates directory
  file:
    path: "{{item}}"
    state: directory
  loop:
    - "{{root_dir}}"
    - "{{root_dir}}/wordpress"

- name: copy Docker Compose files
  template:
    src: wordpress/docker-compose.yaml.j2
    dest: "{{root_dir}}/wordpress/docker-compose.yaml"

